[project]
name = "hexlet-hello-world"
version = "0.1.0"
description = "Auv ve"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.1",
    "more-itertools>=10.7.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pytest>=8.4.0",
]
